name: lint and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: Run pytest
      run: |
        pytest --cov=src --cov-report=term-missing --cov-branch